---
- name: Gnome - Enable touchpad tap-to-click.
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
    state: present

- name: Gnome - Show hidden files.
  community.general.dconf:
    key: "/org/gtk/settings/file-chooser/show-hidden"
    value: "true"
    state: present

- name: Gnome - Update sleep-inactive-ac-timeout to 7200.
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "7200"
    state: present

- name: Gnome - Add keybindings to switch windows.
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
    state: present

- name: Gnome - Add keybindings to switch windows backward.
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"
    state: present

- name: Gnome - Add keybindings to run 'gnome-terminal' - 'binding' key
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Control><Alt>t'"
    state: present

- name: Gnome - Add keybindings to run 'gnome-terminal' - 'command' key
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'/usr/bin/ptyxis --new-window'"
    state: present

- name: Gnome - Add keybindings to run 'gnome-terminal' - 'name' key
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Terminal'"
    state: present

- name: Gnome - Add keybindings to run 'gnome-terminal' - 'custom-keybindings' key
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    state: present

- name: Gnome - Remap 'Caps Lock' key to 'Escape' key
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:escape']"
    state: present

- name: Ptyxis - Update 'move to next tab' keybinding
  community.general.dconf:
    key: "/org/gnome/Ptyxis/Shortcuts/move-next-tab"
    value: "'<Control>k'"
    state: present

- name: Ptyxis - Update 'move to previous tab' keybinding
  community.general.dconf:
    key: "/org/gnome/Ptyxis/Shortcuts/move-previous-tab"
    value: "'<Control>j'"
    state: present
